version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: students_db
    ports:
      - "5432:5432"
  students-service:
    build:
      context: .
      dockerfile: Dockerfile.backup
    image: students-service2:latest
    container_name: students-service
    ports:
      - "8086:8080"
    depends_on:
      - postgres

