name: Desplegar app java

on:
  push:
    branches:
      - main
jobs:
  construir_contenedor:
    runs-on: ubuntu-latest
    steps:
      - name: clonar repositorio
        uses: actions/checkout@v4.1.7

      - name: Instalando jdk 21
        uses: actions/setup-java@v4
        with:
            java-version: 21
            distribution: 'corretto' # Alternative distribution options are available.

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # Build the application
      - name: Build with Maven
        run: mvn clean package

      - uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
            app-name: 'appstudets'
            slot-name: 'production'
            package: 'target/students-service-0.0.1-SNAPSHOT.jar'
