name: Desplegar app java

on:
  push:
    branches:
      - main
jobs:
  construir_contenedor:
    runs-on: ubuntu-latest
    steps:
      - name: clonar repositorio
        uses: actions/checkout@v4.1.7

      - name: Instalando jdk 21
        uses: actions/setup-java@v4
        with:
            java-version: 21
            distribution: 'corretto' # Alternative distribution options are available.

      - name: Compilar proyecto java
        run: |
            ./mvnw clean install
      - name: Compilar proyecto java
        run: |
            java -jar students-service-0.0.1-SNAPSHOT.jar --server.port=8080
