name: Crear imagen docker de students

on: 
    push:
        branches:
            - develop
            - main
    pull_request:
        branches:
            - develop
            - main


jobs:
    construir_contenedor:
        runs-on: ubuntu-latest
        steps:
            - name: clonar repositorio
              uses: actions/checkout@v4.1.7

            - name: instalar Docker
              run: |
                sudo apt-get update
                sudo apt-get install -y docker.io
                sudo systemctl start docker
                sudo systemctl enable docker
                docker --version  # Verifica que Docker esté instalado
      
            - name: instalar Docker Compose
              run: |
                sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                sudo chmod +x /usr/local/bin/docker-compose
                docker-compose --version  # Verifica que Docker Compose esté instalado
            - name: Build and run with Docker Compose
              run: |
                docker-compose up --build -d  # Inicia los contenedores en segundo plano
                docker-compose ps               # Muestra los contenedores en ejecución
            
            - name: Run tests
              run: |
                docker-compose exec students-service ./run-tests.sh  # Reemplaza students-service con el nombre del servicio que deseas utilizar
            - name: Stop and remove containers
              run: docker-compose down
